description: Local LLM Eval Harness

providers:
  - id: http
    config:
      url: http://127.0.0.1:8000/answer
      method: POST
      body:
        question: "{{question}}"

prompts:
  - "{{question}}"

tests: file://testcases.csv

assert:
  - type: contains
    value: "{{expected}}"
  - type: equals
    value: "PASS"
    transform: output.hallucination_check

  - type: equals
    value: "{{expected_hallucination}}"
    transform: output.hallucination_check

  - type: greater-than
    value: "0.7"
    transform: output.context_precision

  - type: greater-than
    value: "0.7"
    transform: output.context_recall
