description: Local LLM Eval Harness

providers:
  - id: http
    config:
      url: http://127.0.0.1:8000/answer
      method: POST
      body:
        question: "{{question}}"

prompts:
  - "{{question}}"

tests: file://testcases.csv

assert:
  - type: contains
    value: "{{expected}}"